### ISSUE TITLE
Clarify multiple registrations by the same participant

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#109]
This issue covers `TckCancelOnTests#cancelFromRemoteCall()` test which makes multiple registrations of the same participant (`LraCancelOnController`) and tests that compensate method has been called several times. This differs from already defined behavior in some tests of `TckTests` class so I would like to propose to clarify this behavior in the spec text or javadoc so that multiple registration of the same participant are ignored and refactor `TckCancelOnTests#cancelFromRemoteCall()` to register two separate participant resources.

**Comment by xstefank** [comment]
@mmusgrov 

> This spec currently requires that participants can only be invoked via JAX-RS endpoints. Since the endpoints uniquely identify the resource and since calling the compensate/complete multiple times is allowed (if there is no status method) there is no ambiguity about multiple registrations.

In here [1] TckTests explicitly test that multiple registration by the same participant are ignored. Additionally `LraController`. However, there is `@Status` annotated method in `LraController`.

If this is the behavior you would prefer it's still requires clarification in the specification. I will create a new PR then with specifying explicitly that multiple registrations of same participant within the same LRA are allowed if there no `@Status` method and there is no need to change TckCancelOnTests then.

> When we change the spec to allow non-JAX-RS based participants can you re-submit the PR and update the issue description to clarify that this issue does not apply to JAX-RS based participant resources.

I don't see why the situation would be any different?

[1] https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/TckTests.java#L435

**Comment by mmusgrov** [comment]
The spec is unambiguous. If there is no @Status annotation the compensate endpoint will be repeatedly called until it reaches one of the end states.

**Comment by xstefank** [comment]
@mmusgrov I still think this may be confusing for users (and implementors) if it is not going to be mentioned explicitly. We are assuming that from the fact you've described it's easy to derive that multiple registrations work when there is no Status method and don't otherwise. But this can be just my view so if you prefer I will close the issue and the PR.

**Comment by mmusgrov** [comment]
The situation is that there is a unique JAX-RS endpoint for the registration in the context of a particular LRA. Therefore a second registration would just be registering the same endpoint ie it would effectively be a null op and therefore there is no need to add any explanatory text to the spec. Unless of course what I have just written is not clear from a reading of the spec.

**Comment by xstefank** [comment]
@mmusgrov I don't understand. You mean unique JAX-RS resource without @Status method? Because this is is conflicting what was written previously.

**Comment by mmusgrov** [comment]
The relevant bits of the spec are:

```
The application developer indicates which JAX-RS method to use for a compensating activity by
annotating it with both the @Compensate and the JAX-RS @PUT annotations. Whenever the associated resource is invoked in the context of an LRA the endpoint corresponding to the @Compensate method MUST be enlisted with the LRA.
```

(a second call the same resource would see the same endpoint so there is no need for a second registration). And annotating more than one method is unspecified:

```
If the @Compensate or @Complete annotation is present on multiple methods then an arbitrary one is
chosen.
```

**Comment by xstefank** [comment]
@mmusgrov so what is your final decision for this issue then?

**Comment by rdebusscher** [comment]
The specification defines that when a `@Complete` or `@Compensate` is successfully called, the LRA should not be considered anymore for further compensate or complete calls anymore (since the state is Cancelled or Closed)

So for me, the TCK test is then wrong if you describe it as follows

> This issue covers TckCancelOnTests#cancelFromRemoteCall() test which makes multiple registrations of the same participant (LraCancelOnController) and tests that compensate method has been called several times. 

We should test that the compensate method is only called once!

**Comment by ochaloup** [comment]
I agree with Rudy. That's why this issue was created. But I think it would be beneficial to explicitly mention this behaviour in the text of  the specification.

**Comment by mmusgrov** [comment]
If we underline every aspect of the spec with additional explanatory text then the spec is going to be long and is not going to be read and will add to peoples misunderstanding of the spec. I explained in my last comment why the spec is already unambiguous on this issue.

**Comment by ochaloup** [comment]
I think it's not clear, for example it was not clear for me.
Personally I think it's good to mention all aspects if possible. Even when the text meaning overlaps a bit (if it does not contradict).

**Comment by mmusgrov** [comment]
Which parts of the of the two quotes are not clear. Instead of adding extra text lets just ensure that what is currently written is clear.

**Comment by mmusgrov** [comment]
As discussed at this weeks hangout @ochaloup is going to propose the new text.
