### ISSUE TITLE
Fix TckCancelOnTests#cancelFromRemoteCall invalid behavior

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#113]
Currently TckCancelOnTests#cancelFromRemoteCall incorrectly assumes that multiple registrations of the same participant in the same LRA result in multiple calls to compensate method.

The proposed fix would be to refactor cancelFromRemoteCall method to a new separate participant and the test would validate that both participants are compensated in the end.

This issue is a follow up on issue #109

**Comment by mmusgrov** [comment]
I asked Ondra to change the existing test to assert that compensate was only called once. The test does not need refactoring.

**Comment by ochaloup** [comment]
@mmusgrov changing the assert to 1 is not the correct solution. It could be that the Narayana implementation will start to pass but the test will be wrong. We can't drive the specification based on what the implementation expects.

Summary of the issue

    I wrote the test cancelFromRemoteCall which tested two separate things "cancel on remote call" and "multiple registration of the same participant"
    this PR changes the test cancelFromRemoteCall in the correct way that the test will be testing only the behaviour of the "cancel on remote call"
    the issue #109 was created based on our discussion to clear the specification "multiple registration of the same participant" and for fixing the failing tests.
    this PR was gradually changed to contain only fix for the test cancelFromRemoteCall and I think it fixes it in the good manner
    we possibly should consider adding a specific test for the "clarify multiple registrations by the same participant" (edit: I can see @xstefank already added that to #92 some time ago)
    I would be glad if we can shortly talk on the hangout if the spec is really clear in the manner of the issue #109

**Comment by mmusgrov** [comment]
The test validates that using the same resource twice within a single transaction where one invocation triggers a cancel of the LRA results in two compensate calls. But that was based on your misreading the spec since only one compensate call is expected. So changing the assert to 1 still results in a valid test:

- it tests that the remote resource cancels the LRA correctly
- it tests that the participant resource was asked to compensate once.

This stuff really isn't all that complicated and I don't know why we keep going round in circles trying to make progress.

**Comment by xstefank** [comment]
if @ochaloup is ok with that I will change the PR

**Comment by ochaloup** [comment]
@xstefank @mmusgrov my persuasion is that the PR https://github.com/eclipse/microprofile-lra/pull/114 clarifies the behaviour and separates the functionality which is tested. I would prefer to use it as it is proposed. I understand the argument about simplicity. But if the test is reasonable and as especially it's a test I can't see it as a blocker for approving it.

As we have here a different opinions on this topic and and I don't wan't to be going in circles, please, let's go with the assert to 1.

**Comment by xstefank** [comment]
superseded by #118
