### ISSUE TITLE
Add TCK for multiple registrations of the same participant within the same LRA

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#119]
Proposed test cases (will be added to issue #92 if accepted)

- [ ] Register through same `@LRA` method twice within same LRA
- [ ] Register through 2 different `@LRA` methods in the same participant resource within same LRA
- [ ] Two registrations in two separate participants results in two compensations being called

**Comment by mmusgrov** [comment]
I'd like to raise the PR for these along the lines of the [following diff](mmusgrov@dee8d90)

**Comment by xstefank** [comment]
@mmusgrov diff is empty. I was going to do this after #115 is merged but if you want to take go ahead

**Comment by mmusgrov** [comment]
Thanks.

The diff is https://github.com/mmusgrov/microprofile-lra/commit/dee8d901eb529601910dd3cbed2cb420cb5e1d52
