### ISSUE TITLE
Add TCK tests verifying functionality of different LRA.Type 

### ISSUE THREAD

**Issue by ochaloup** [eclipse/microprofile-lra#120]
The `LRA.Type` (https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/LRA.java#L123) defines the LRA scope the invocation belongs to. The TCK should contain tests which verify whether all the `Type`s are correctly handled.

- [ ] `Type.REQUIRED` : if LRA context exists it joins it
- [ ] `Type.REQUIRED` : if LRA context does not exist it creates new LRA
- [ ] `Type.REQUIRES_NEW` : if LRA context exists it creates new LRA
- [ ] `Type.REQUIRES_NEW` : if LRA context does not exist it creates new LRA
- [ ] `Type.MANDATORY` : if LRA context exists it joins LRA
- [ ] `Type.MANDATORY` : if LRA context does not exist it fails with `412, precondition failed`
- [ ] `Type.SUPPORTS` : if LRA context exists it joins LRA
- [ ] `Type.SUPPORTS` : if LRA context does not exist it does not join LRA (running outside scope of LRA)
- [ ] `Type.NOT_SUPPORTED` : if LRA context exists the method is executed outside of the scope
- [ ] `Type.NOT_SUPPORTED` : if LRA context does not exist the method is executed outside of the scope
- [ ] `Type.NOT_SUPPORTED` : if LRA context exists the context is suspended and resumed(!) at the end of the annotated method
- [ ] `Type.NEVER` : if LRA context exists it fails with `412, precondition failed`
- [ ] `Type.NEVER` : if LRA context does not exist it executes outside of the LRA context

**Comment by xstefank** [comment]
@ochaloup +1 great idea. One small request: each bullet point here should really be mostly two test cases in my opinion

**Comment by ochaloup** [comment]
@xstefank thanks, I changed the description

**Comment by mmusgrov** [comment]
+1
