### ISSUE TITLE
Invalid assert in TCK mixedMultiLevelNestedActivity test

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#125]
In mixedMultiLevelNestedActivity test precisely [in this check](https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/TckTests.java#L540) TCK tries to verify that 2 nested LRAs that were completed when the rest invocation was finished are still active because enclosing parent LRA is still active. However, this check could work previously when get active LRAs returned list of active LRAs from the framework but now it tries to enlist within the LRA to verify that it is finished. This means that this check 2b tries to enlist with these 2 already completed nested LRAs which is not possible. 

I would propose to remove this check.

**Comment by mmusgrov** [comment]
Good catch, this explains why I couldn't get it working when we replace LRAClient.
