### ISSUE TITLE
Remove package org.eclipse.microprofile.lra.client from the API

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#137]
The org.eclipse.microprofile.lra.client package should have been removed when the Java Client API was removed in issue #95 and this new issue will remove it. The only things left in the client API package are the exception types (GenericLRAException, IllegalLRAStateException, InvalidLRAIdException and UnknowableException) which are no longer required.

**Comment by xstefank** [comment]
+1

**Comment by mmusgrov** [comment]
PR merged
