### ISSUE TITLE
Add a specification note about how applications can use LRAs in reactive environments

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#149]
The specification is designed for use with JAX-RS which supports asynchonous operations via:

- JAX-RS `@Suspended` annotation
- Java 8 CompletionStages

We need a section that shows examples and we also need some TCK tests to verify that implementations operate correctly when services use these async features.

**Comment by xstefank** [comment]
@mmusgrov can this be closed? Both PRs are merged.
