### ISSUE TITLE
Allow String parameters as parameter type for Complete and Compensate Methods in the non JAX-RS case

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#160]
Through Issue https://github.com/eclipse/microprofile-lra/issues/35 (PR https://github.com/eclipse/microprofile-lra/pull/148) the only allowed parameter type on the Complete and Compensate Methods is `java/net.URI`

    @Compensate
    public void compensateAction(URI lraId) {

However, in the JAX-RS version, the most common parameter types will be String.

    @PUT
    @Path("/compensate")
    @Produces(MediaType.APPLICATION_JSON)
    @Compensate
    public Response compensateWork(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) String lraId) {

In order to make the spec more uniform, String should also be allowed as parameter types for Complete and Compensate Methods in the non JAX-RS case.

    @Compensate
    public void compensateAction(String lraId) {

**Comment by mmusgrov** [comment]
I am sorry Rudy, on the gitter room when I said I agreed I thought you were talking about the opaque user data on callbacks but when I checked the spec I see that we deferred #15 to milestone 2.

In issue #105 we agreed on URI so I think all we need to do is change all of our examples to use a URI for the  header. Note also that JAX-RS header parameters can be of any data type.

**Comment by rdebusscher** [comment]
>Also I don't think the goal should be to exactly mimic what the corresponding JAX-RS methods are doing.

No, but it makes the implementation easier in this case. Since Payara will always use the Proxy approach, since there will be no REST communication between Participant and _'coordinator'_, the allowed parameter types of the method will be different depending on the fact if there is a JAX-RS method (like @PUT) defined or not.

**Comment by rdebusscher** [comment]
URI is the only type we support. See also #163.
