### ISSUE TITLE
Spec: Indicate that LRA id MUST be of type URI

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#163]
After the implementation of #35, but internal the already before the implementation of this, LRA id MUST be of type URI.

So we need to indicate this requirement in the spec. 
We should change all examples in the spec where we use @HeaderParam(LRA_HTTP_CONTEXT_HEADER) and @HeaderParam(LRA_HTTP_PARENT_CONTEXT_HEADER) to URI to be consistent.

We can indicate in a note that String will work due to the conversion within JAX-RS, but only when the method is a JAX-RS method.

**Comment by rdebusscher** [comment]
The recovery ID is also indicated as a URI in the JavaDoc. We can mention this also in the Spec text.

**Comment by rdebusscher** [comment]
Update the TCK for using URI instead of String

**Comment by mmusgrov** [comment]
https://github.com/eclipse/microprofile-lra/pull/165 resolves this issue
