### ISSUE TITLE
LRA - how to implement a model driven approach? 

### ISSUE THREAD

**Issue by rsoika** [eclipse/microprofile-lra#179]
Hi, 
I am very interested in LRA as a way to implement the Microservice SAGA pattern.
We develop a Open Source Workflow engine ( [imixs-workflow](https://www.imixs.org) )based on Java EE and we already adopted the Eclipse Microprofile API (config, metrics).

I already wrote an article about business transactions in Microservice environments where the transaction is described in a BPMN model: https://dzone.com/articles/microservices-and-business-transactions

I am interested to try an implementation of LRA in combination with our workflow engine. 
One of my question is if it is/will be possible to add participants at runtime or if I need to annotate everything at build time? The question is from the point of a model driven approach where the workflow engine is the coordinator and the model describes the different participants. 

I know it is an early stage, but what is necessary to try LRA? We already run on Payara.

**Comment by xstefank** [comment]
Hi @rsoika, hopefully, I will be able to answer some of your questions:

> I am very interested in LRA as a way to implement the Microservice SAGA pattern.
We develop a Open Source Workflow engine ( imixs-workflow )based on Java EE and we already adopted the Eclipse Microprofile API (config, metrics).

> I already wrote an article about business transactions in Microservice environments where the transaction is described in a BPMN model: https://dzone.com/articles/microservices-and-business-transactions

> I am interested to try an implementation of LRA in combination with our workflow engine.

That's great!
 
> One of my question is if it is/will be possible to add participants at runtime or if I need to annotate everything at build time? The question is from the point of a model driven approach where the workflow engine is the coordinator and the model describes the different participants.

We used to have [an API for runtime registration](https://github.com/eclipse/microprofile-lra/blob/e71efb0071e791a26e9ebba78740ddd2aea3273a/api/src/main/java/org/eclipse/microprofile/lra/participant/LRAManagement.java#L46) but it was removed for 1.0. However, it is possible that something similar will be included in any of the 1.x releases if there will be a community request which we now have, I believe.

> I know it is an early stage, but what is necessary to try LRA? We already run on Payara.

@rdebusscher created the Payara implementation so he will be the contact person for Payara related questions. Another option is [Narayana implementation](https://github.com/jbosstm/narayana/tree/master/rts/lra) where you can contact @mmusgrov or me with questions.

**Comment by rdebusscher** [comment]
Hi Ralph,

Regarding the Payara Support,

The dynamic registration will not be standardized in the 1.0 specification
as mentioned, but it will be possible to use a Java API to handle the
participants at runtime within Payara Server and Payara Micro.

Currently, the implementation is in an early stage, but if you are
interested in a beta version later on, let me know.

Regards
Rudy

**Comment by rsoika** [comment]
I am just reading the spec and try to map the concept to my workflow engine.

My question is now: is a LRA persisted in any way, or are they only stored in the ApplicationScoped client class? I ask this because I want to understand what happens when I have actions that take several hours and I have to manage several thousand such actions.

**Comment by xstefank** [comment]
This should be the choice and the responsibility of the implementation. The specification [says that](https://github.com/eclipse/microprofile-lra/blob/master/spec/src/main/asciidoc/microprofile-lra-spec.adoc#324-compensating-activities): 

> The application developer indicates which method to use for a compensating activity by marking it with the @Compensate annotation. Whenever the associated resource is invoked in the context of an LRA the method corresponding to this @Compensate method MUST be enlisted with the LRA: enlistment means that if the LRA is subsequently cancelled then the compensation method MUST be invoked.

**Comment by rdebusscher** [comment]
Ralph,

LRA status and info around the participants who have joined the LRA are
persisted. (since the spec says it guarantees the Eventual Persistent
outcome.)

There is no issue that an action takes several hours, that is why they are
called Long Running Actions :) Of course, the LRA implementation needs to
store the information of each on going action.

The current implementations don't store information in an ApplicationScoped
class (also because it needs to work in a distributed environment where an
actions spans multiple requests located on multiple servers.) For Narayana
it is a dedicated process which is responsible for this, and Payara uses
the Payara DataGrid for this purpose.

Regards
Rudy

**Comment by mmusgrov** [comment]
@rsoika Thanks for raising the issue. It looks like the question has been answered so I am closing it. If you have further thoughts or questions then please either reopen it or raise a new question.
