### ISSUE TITLE
Split the proposal into two separate sections: one for the API and one for JAX-RS transport

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#18]
To ensure that the spec has broader applicability the JAX-RS specific aspects of the API need to be pulled out into a separate section.

This change would also enable a cleaner definition of the wire protocol with the main option being JAX-RS and in particular would provide a natural place to document how participants running against one implementation of this specification can register with other implementations (see #17).

**Comment by WillemJiang** [comment]
Hi Michael,
Current in ServiceComb-Saga implementation, we just use GRPC to send events coordinator, [here ](https://github.com/apache/incubator-servicecomb-saga/blob/master/docs/design.md)are our design document for it.  I think we can work together to polish the specification.

**Comment by mmusgrov** [comment]
We discussed this issue at the last hangout and the consensus (Emily and myself) was that we should start with smaller steps and target the initial proposal towards the baseline JAX-RS. I therefore would like to close this issue as will not fix.

Support for other protocols such as gRPC can be supported using vendor adaptors.

**Comment by mmusgrov** [comment]
@zhfeng I withdrew PR jbosstm#5 since the plan is to keep the dependency on JAX-RS in the initial MP LRA proposal. We can still interoperate with other models by providing an adaptor component to proxy the two models. Tom came up with a [technique](https://github.com/eclipse/microprofile-lra/issues/17#issuecomment-421284637) for doing this on issue #17 which I think would make sense to include in the SmallRye implementation.
