### ISSUE TITLE
SPEC: Indicate effect LRAid Unknown response by participant on LRA statis

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#194]
(retyped)

The call to the @complete and @compensate methods/endpoints are allowed to return "LRAid unknown" (through HTTP status 404 or 410 is we decide that that code is better suited). We need to clarify in the spec what the effect on the LRA status is.

The effect depends on the call history for that participant (are we in the retry mode), in other words, is this the first call from the implementation to this method/endpoint or subsequent calls.

- When the response is "LRAid unknown" when the implementations calls the @complete or @compensate methods/endpoints, the participant status MUST be `FailedToComplete` or `FailedToCompensate` (depending on the action which was performed). The LRAStatus becomes than `FailedToClose` or `FailedToCancel` (based on the standard rules/flow for the LRA Status)

- When the response is "LRAid unknown" after a successful call the @complete or @compensate methods/endpoints, the  participant status MUST be `Completed` or `Compensated`. Again the LRA Status is determined by standard rules/flow.

- When a call to @status method/endpoint returns "LRAid unknown" the  participant status MUST be `Completed` or `Compensated`.

**Comment by mmusgrov** [comment]
If "410 Gone" seems a good alternative for the 404 cases we have now then the effect should just be for the implementation to retry the request. The retry policy is being discussed on issue #190

**Comment by rdebusscher** [comment]
hmm, seems that Github has removed all my comments and explanation I made :(

I'll type in everything again

**Comment by xstefank** [comment]
@rdebusscher there is another issue #195 which seems to contain your comments

**Comment by rdebusscher** [comment]
thanks @xstefank. This can be closed (and deleted by admins) then!
