### ISSUE TITLE
SPEC: Indicate effect LRAid Unknown response by participant on LRA status

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#195]
A call to the @Complete and @Compensate methods/endpoints are allowed to return with a result of "LRAid Unknown" (HTTP status 404 - or 410 when we decide that that response code is better suited)

The result on the LRA status is depending on the existence of previous call (are we in 'retry' mode) and is as follows

- When the first call to @Complete and @Compensate methods/endpoints results in "LRAid Unknown" the status of the Participant becomes `FailedToComplete` or `FailedToCompensate` (depending on the action) and LRA status becomes FailedToClose or FailedToCancel. (according to the general rules)

- When another call (not the first) to @Complete and @Compensate methods/endpoints results in "LRAid Unknown" the status of the Participant becomes `Completed` or `Compensated` (depending on the action) and LRA status becomes is defined according to the general rules.

- When a call to the @Status method/endpoint results in "LRAid Unknown" the status of the Participant becomes `Completed` or `Compensated` (depending on the action) and LRA status becomes is defined according to the general rules.

**Comment by rdebusscher** [comment]
Background info

When the first call to @complete and @compensate methods/endpoints result in "LRAid Unknown", it  is in contrast with the protocol (the Participant is in state Active at the time of the first call and thus need to know about the LRA)
So the status change to FailedToxxx is a logical one.

When a later call to these methods/endpoints results in "LRAid Unknown", a first call was acknowledged with a `Completing` or `Compensating` status. The "LRAid Unknown" indicates that the Participant activity is finished successfully and that LRAid is already forgotten (which is allowed when Participant successfully finished the process). So 'normal' ending is assumed.

A call to the @status is only performed after an initial successful call to @complete and @compensate methods/endpoints. So the same reasoning can be used as above and Participant should be considered as `Completed` or `Compensated`.

**Comment by rdebusscher** [comment]
Need spec update (clarification) and TCK tests

**Comment by mmusgrov** [comment]
1. If the implementation asks a participant to compensate and it does so then the participant may forget about the LRA (if it fails to compensate then it MUST remember it failed and report the status when asked until it is explicitly told to Forget). 
1. In the successful case the participant may clean up and respond with 410 to any further requests involving this LRA (of course it is allowed to report that it compensated but that does not add anything to the protocol) 
1. If the compensate end point is invoked by some other entity then the participant MUST remember what it did so that it can respond correctly to the implementation. NB if the compensation endpoint is not secured it should check for the presence of the LRA#LRA_HTTP_RECOVERY_HEADER header since only the implementation will set that (we do not support malicious entities).

Do we need to say anything more than this?

**Comment by mmusgrov** [comment]
I don't think we need to say anything about first and second calls since that is confusing. The participant could compensate and legitimately return 410 to both of them - ie it would not effect the guarantees that our protocol provides.

**Comment by mmusgrov** [comment]
Perhaps we should put the protocol description in the "The Model" section of the spec. That way the reader would have a mental model to refer to when reading the rest of the spec.

**Comment by rdebusscher** [comment]
Consensus from Gitter discussion.

We advice in the spec that developers should never set the header `LRA#LRA_HTTP_RECOVERY_HEADER` themselve. That way developers can distinguish between a end-user call and an implementation call to JAX-RS participant methods (like @complete and @compensate)

Since there is also the following statement in the spec (where these refer to @complete or @compensate annotated JAX-RS resources)
>LRA implementation MUST ensure that invoking these methods outside of the 
implementation of the LRA specification will not influence any running LRA.

We can assume that when a @complete or @compensate method return status "410 Gone" (previously status 404) the participant has performed all actions required to complete or compensate the action and thus the participant Status MUST be considered `Completed` or `Compensated`.

The same holds for a response with status 410 when the @Status endpoint is called.

**Comment by mmusgrov** [comment]
@rdebusscher Can you raise a PR for this please

**Comment by rdebusscher** [comment]
@mmusgrov I'm working on the PR
