### ISSUE TITLE
TCK: Make name JAX-RS resource classes uniform

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#202]
Some of the Test JAX-RS classes with endpoints are ending on `Resource`, other on `Controller`.

They should have a uniform name.

**Comment by rdebusscher** [comment]
Controller: +1
Resource: 0

**Comment by mmusgrov** [comment]
The are resources so +1 to Resource

**Comment by xstefank** [comment]
I am also for Resource as Controller is more Spring-like for me.

Controller: 0
Resource: +1

**Comment by mmusgrov** [comment]
Not all of our resources have Models and Views so Controller would give the wrong impression whereas they are all JAX-RS resources.

**Comment by mmusgrov** [comment]
Can we close the voting for this issue and create a PR. @rdebusscher who should raise the PR?
