### ISSUE TITLE
LRA_HTTP_RECOVERY_HEADER is mandatory for the participant methods

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#209]
When the implementation calls the participant callback methods - as JAX-RS endpoints (complete, compensate, status, forget, afterLRA) it MUST add the LRA_HTTP_RECOVERY_HEADER to indicate the request comes from the implementation.

Update the https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/participant/api/LraResource.java (amongst others) within TCK to validate the presence of the LRA_HTTP_RECOVERY_HEADER

**Comment by mmusgrov** [comment]
Is this issue a reference the spec item:

> annotated with `@Complete`). In addition the implementation should generate a
URI for this participant and make it available to the business logic via a JAX-RS
header param with name defined by the Java constant `LRA_HTTP_RECOVERY_HEADER` as defined

In particular are you asking for the word "should" to be replaced with "MUST"?

**Comment by rdebusscher** [comment]
@mmusgrov  For me it is not important that implementation adds the `LRA_HTTP_RECOVERY_HEADER` header to the JAX-RS business methods. (as it is not useful for the developer I think)

But as discussed on #205, the implementation MUST add the header  `LRA_HTTP_RECOVERY_HEADER` to @Complete, @Compensate, @AfterLRA, and @Forget endpoints (JAX-RS version only of course) so that developer can distinguish between call made by the system and call made by developer.
