### ISSUE TITLE
TCK: Conflicting tests regarding LRA.Type.MANDATORY

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#210]
2 tests within the TCK are using a conflicting interpretation of the spec and JavaDoc.

**org.eclipse.microprofile.lra.tck.TckLRATypeTests#requiredWithClosedLRA**

Calls an endpoint with Type.MANDATORY with an LRAid which belongs to a no longer active LRA.
It checks if the implementation has created a new LRAid for this call.

**org.eclipse.microprofile.lra.tck.TckTests#cancelLRA**

calls an endpoint with Type.MANDATORY with an LRAid to check if the LRA is still active. When not active, it expect a return status code of 412.

**LRA.Type.MANDATORY JavaDoc**

         *     If called outside an LRA context the method is not executed and a
         *     <code>412 Precondition Failed</code> HTTP status code is returned
         *     to the caller.

**Comment by rdebusscher** [comment]
The logic within the test org.eclipse.microprofile.lra.tck.TckLRATypeTests#requiredWithClosedLRA is therefore wrong.

It should use the status code return code to see if the LRA was active or not (412 vs 200)

**Comment by xstefank** [comment]
The test `org.eclipse.microprofile.lra.tck.TckLRATypeTests#requiredWithClosedLRA` was proposed in https://github.com/eclipse/microprofile-lra/issues/166#issuecomment-503411278. I believe the behavior is expected.

The test `org.eclipse.microprofile.lra.tck.TckTests#cancelLRA` starts a new LRA and then calls an `LRA.Type.MANDATORY` endpoint to close it, therefore, the LRAid is still active and the call should pass without issues.

I agree with you that JavaDoc for MANDATORY should be adjusted to "If called outside an active LRA context".

**Comment by xstefank** [comment]
Sorry about the previous comment, you are talking about the assert statement. Your concern is right. Let me fix it, please.

**Comment by rdebusscher** [comment]
@xstefank forget it. I'm staring already too long to the TCKs and mixed it up.

`org.eclipse.microprofile.lra.tck.TckLRATypeTests#requiredWithClosedLRA` is using a REQUIRED endpoint (and not mandatory), and thus should just create a new LRAid and return status 200.

There is nothing wrong with those 2 tests.

**Comment by xstefank** [comment]
yeah, I guess me too :) we are checking in `isLRAFinished` for PRECONDITION_FAILED already :+1:
