### ISSUE TITLE
TCK: Add test where LRA is cancelled due to timeout on @Compensate

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#232]
No such Test is available today.

**Comment by xstefank** [comment]
I think @mmusgrov was already working on this kind of tests.

**Comment by rdebusscher** [comment]
Good, then we now have an Issue for it and we can track the progress.

When there is no issue for it, other people don't know that info.

**Comment by mmusgrov** [comment]
> Good, then we now have an Issue for it and we can track the progress.
> 
> When there is no issue for it, other people don't know that info.

https://github.com/eclipse/microprofile-lra/issues/6

**Comment by mmusgrov** [comment]
In the original PR for that issue I had 5 or 6 time limit based tests. The PR review was delayed by quite a while and my change set no longer merged cleanly when it was finally reviewed - hence the delay is re raising the PR.

**Comment by mmusgrov** [comment]
So this is a duplicate of #6. Why don't we/I add more text to #6 saying what the original PR tested

**Comment by mmusgrov** [comment]
So can add clarification to issue #6 and close this issue as a duplicate?

**Comment by rdebusscher** [comment]
Added tests to #6, see https://github.com/eclipse/microprofile-lra/issues/6#issuecomment-535839247
