### ISSUE TITLE
Clarify Type.NEVER and what a LRA context is.

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-lra#243]
Based on a discussion around following example, a JAX-RS endpoint defined as this

@Path("/someEndpoint")
@LRA(Type.Never)
public Response doSomething() {}

which will be called with an inactive LRAid In the header.

**Comment by rdebusscher** [comment]
The outcome is that the implementation will not check if the LRAid is active or not. The fact the header is present is enough to determine if the method can be executed or not.

**Comment by mmusgrov** [comment]
Why doesn't the [text](https://github.com/eclipse/microprofile-lra/issues/244#issuecomment-542704650) on issue #244 cover this.

**Comment by rdebusscher** [comment]
Just adding that one line in the spec is not enough as there are a lot of places which contradict each other.

In the case of Type.NEVER, you cannot even define it as participant (well it doesn't make sense), but the fail needs to happen in all cases. So it is best to explicitly describe what the implementation does need to do and what the developer can expect.

**Comment by mmusgrov** [comment]
> Based on a discussion around following example, a JAX-RS endpoint defined as this
> 
> @path("/someEndpoint")
> @lra(Type.Never)
> public Response doSomething() {}
> 
> which will be called with an inactive LRAid In the header.

And the method will not execute and the caller will receive a 412 error since NEVER means never execute with a context (even an inactive one). Why is this an issue?

**Comment by rdebusscher** [comment]
As it is not clear enough what 'inside' and 'outside' context actually means.

For example, when calling the endpoint with some rubbish URI in the header.
