### ISSUE TITLE
Document the behavior of failed Complete/Compensate calls with Status method present in the resource

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#283]
If there is a Status method present in the resource the specification assumes that Complete/Compensate methods are not idempotent. This means that the implementation should not invoke the Complete/Compensate repeatedly in case the Status method is available.

However, if the Complete/Compensate is invoked successfully but the response is lost, the implementation may assume that the Complete/Compensate call didn't happen at all and try to reinvoke these methods which would be an erroneous behavior. Also, the user needs to know that this kind of situation can happen and in case the Status is called before Complete/Compensate to invoke the relevant operation themselves.

I believe this needs to be documented scenario in the spec text.

**Comment by rdebusscher** [comment]
I have some remarks on your reasoning.

You mention "in the case the complete/compensate is called successfully, but the response is lost" this means the actual logic within those methods are executed and thus there is no issue in calling the status method.

But clarification could be needed in the case the implementation calls the complete/compensate methods but those methods are actually never been called.
I think we can say that when a HTTP status is returned, the method is executed and it is safe to call Status. Otherwise (like with connection errors) those methods are re-executed by the implementation.
For the non-JAX-RS case, I need to have a look what should be the correct behaviour.

**Comment by xstefank** [comment]
@rdebusscher I am aiming more to not repeat the execution of the Complete/Compensate (eg. Compensate call times out and the implementation retries it instead of calling status).

> You mention "in the case the complete/compensate is called successfully, but the response is lost" this means the actual logic within those methods are executed and thus there is no issue in calling the status method.

There is no issue in calling Status at any point in LRA execution. I am aiming at not repeating Complete/Compensate when the logic in them is executed already once before.

> I think we can say that when a HTTP status is returned, the method is executed and it is safe to call Status. Otherwise (like with connection errors) those methods are re-executed by the implementation.

+1 I like this reasoning.

> For the non-JAX-RS case, I need to have a look what should be the correct behaviour.

Non-JAX-RS case should be handled by the implementation. The in-VM call to non-JAX-RS method can only fail with exception and this behavior is described by non-JAX-RS cases contract. So this shouldn't be a problem. Repeated calls should be detected by the implementation.

**Comment by mmusgrov** [comment]
If the implementation doesn't know the outcome of the complete/compensate call then it checks the status method. If the participant missed the call it reports `ParticipantStatus.Active` otherwise it reports the actual status. I don't see why we need new text. Which bit of the spec is unclear.

**Comment by xstefank** [comment]
Is that explicitly mentioned? You are correct but TBH I don't think that when I was writing Status methods before I was thinking about this use case. It would be better to have this explicitly stated for both implementors and users.

**Comment by mmusgrov** [comment]
I believe the javadoc for the `@Status` annotation covers this scenario:

> LRA annotations support distributed communications amongst software components and due to the unreliable nature of networks, messages/requests can be lost, delayed or duplicated etc and the implementation component responsible for invoking Compensate and Complete annotated methods may loose track of the status of a participant. In this case, ideally it would just resend the completion or compensation notification but if the participant (the class that contains the Compensate and Complete annotations) does not support idempotency then it must be able to report its' status by by annotating one of the methods with this @Status. The annotated method should report the status according to one of the ParticipantStatus enum values.

**Comment by ochaloup** [comment]
The javadoc of the `Status` method talks about this situation in details. The LRA spec then contains the first part of that text which is part of the javadoc.

* enhancing the spec with the particular example that Martin talks about would be beneficial. For whoever reading the documentation will understand better the purpose of the `Status` with the particular illustration.
* the spec talks about the status `410` and says `in the case of non-JAX-RS method returning ParticipantStatus null`. I searched in javadoc of https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ParticipantStatus.java to understand more about the `null` meaning but I can't find there anything. For my understanding, where is declared the meaning of `null` returned as `ParticipantStatus`? Why the spec push to use `null` as a valid response when any `null` instance leads to possible `NullPointerException`?
* the last sentence of the paragraph on the `Status` says that `This enables the participant to free up resources.`. That statement states that returning `410` or `null` makes participant to free up resources... right (do I misread it)? Which is a wrong interpretation as participant is free to free up the resources at time the complete/compensate finished sucessfully.

@mmusgrov the javadoc seems to cover the scenario but is not clear for anybody outside. Do you particularly object against such elaboration in the spec for some reason? Or is it ok to proceed with an update. (@xstefank I can sketch something)

**Comment by xstefank** [comment]
> Why the spec push to use null as a valid response when any null instance leads to possible NullPointerException?

In non-JAX-RS cases, users can always return null (we can't enforce non-nullable results) so we gave the null value a meaning. The meaning of returned `null` is the same as 410 (as you mentioned) basically the participant does not hold any knowledge about this enlistment. 410 is basically a valid completion or compensation for semantic purposes.

It shouldn't lead to a null pointer as this is a contract defined by the specification and the returned null value is handled by the specification implementation not by the user. There should be a TCK testing it. If not, we should add it.

> the last sentence of the paragraph on the Status says that This enables the participant to free up resources.. That statement states that returning 410 or null makes participant to free up resources... right (do I misread it)? Which is a wrong interpretation as participant is free to free up the resources at time the complete/compensate finished sucessfully.

lol :), it should be: The response code 410
 * which is received when calling this Status annotated method, MUST be interpreted by the implementation
 * that the process is successfully completed and the participant already **forgot** about the LRA.

@ochaloup go ahead with the PR, thanks!

**Comment by mmusgrov** [comment]
> ... Also, the user needs to know that this kind of situation can happen and in case the Status is called before Complete/Compensate to invoke the relevant operation themselves.

What does "invoke the relevant operation themselves" mean?

**Comment by mmusgrov** [comment]
> The javadoc of the `Status` method talks about this situation in details. The LRA spec then contains the first part of that text which is part of the javadoc.
> 
> * enhancing the spec with the particular example that Martin talks about would be beneficial. For whoever reading the documentation will understand better the purpose of the `Status` with the particular illustration.

As long as more text does not divert attention from the basic meaning of the Status method (which we should be able to state succinctly). To much documentation can lead to misunderstanding too due to perceived complexity (the perception in the reader is that if it takes a lot of words to explain then it must be complicated which I don't think it is).

> * the spec talks about the status `410` and says `in the case of non-JAX-RS method returning ParticipantStatus null`. I searched in javadoc of https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ParticipantStatus.java to understand more about the `null` meaning but I can't find there anything. For my understanding, where is declared the meaning of `null` returned as `ParticipantStatus`? Why the spec push to use `null` as a valid response when any `null` instance leads to possible `NullPointerException`?

Remark: Before we had the ParticipantStatus.Active state a null value indicated that the participant had not yet been asked to finish but hopefully we updated all instances of this interpretation.

But now, as Martin alluded, it is used to indicate that a non JAX-RS participant does not know about the LRA (because it did the correct action and cleaned up).

> * the last sentence of the paragraph on the `Status` says that `This enables the participant to free up resources.`. That statement states that returning `410` or `null` makes participant to free up resources... right (do I misread it)? Which is a wrong interpretation as participant is free to free up the resources at time the complete/compensate finished sucessfully.

I don't really understand this statement [in section 3.2.10 of the spec] either since a participant should only free up resources when it has successfully compensated or completed, ie cleaning up resources has nothing to do with the Status method. I would advise that you just delete the statement.

> 
> @mmusgrov the javadoc seems to cover the scenario but is not clear for anybody outside. Do you particularly object against such elaboration in the spec for some reason? Or is it ok to proceed with an update. (@xstefank I can sketch something)

Go ahead but I would prefer minimalism. If we expand our documentation too far then the reader will suffer from information overload.
Ideally, I would prefer the existing text to be improved but kept minimal and accurate.

**Comment by mmusgrov** [comment]
@ochaloup Also notice that we already have examples of how to use the @Status method on pages 15 and 16 (section 3.2.4. Compensating Activities) of the spec.

**Comment by xstefank** [comment]
> What does "invoke the relevant operation themselves" mean?

Sorry, I probably took this from an implementation perspective. So if the participant can't ask the implementation about the LRA outcome (if it doesn't know about the received LRA id) then it can't invoke complete/compensate itself. We can do that in Narayana but it's not specified.

**Comment by mmusgrov** [comment]
> > What does "invoke the relevant operation themselves" mean?
> 
> Sorry, I probably took this from an implementation perspective. So if the participant can't ask the implementation about the LRA outcome (if it doesn't know about the received LRA id) then it can't invoke complete/compensate itself. We can do that in Narayana but it's not specified.

I still don't know what you mean. If a participant makes a unilateral decision then it is obliged to remember its decision and report it via the standard callbacks. We already state this in the spec so we do not need any further clarification.

I would urge us not to mix concepts in the specification otherwise nobody is going to be able to read/understand our spec.

**Comment by xstefank** [comment]
@mmusgrov don't worry about that. Let's go with Rudy's suggestion:

> I think we can say that when an HTTP status is returned, the method is executed and it is safe to call Status. Otherwise (like with connection errors) those methods are re-executed by the implementation.

For the status documentation itself, I don't need anything else than what was proposed in different PRs until now.

@ochaloup do you want to work on this issue?
