### ISSUE TITLE
Refactoring the TCK test classes to separate their purposes in a cleaner way

### ISSUE THREAD

**Issue by ochaloup** [eclipse/microprofile-lra#294]
There are currently two TCK test classes `TCKTests` and `TCKRecoverytTests`. Especially with fixes which came with `@ArquillianResource URL url` injection and the later one (https://github.com/eclipse/microprofile-lra/pull/291, https://github.com/eclipse/microprofile-lra/pull/292) it can be seen that they are not sharing the same processing.

The `TCKRecoveryTests` is meant to be run as `@RunAsClient` mode where the URL injection does not work and need to be passed by remote url call as http header attribute. While the `TCKTests` is in-container test running with full fledged injection capabilities.

From that it would be good to split those tests to not share the same parent class as they are managed in a different way and the `TCKRecoveryTest` should be explicitly marked as running outside of the container.

**Comment by mmusgrov** [comment]
1.x milestone sounds reasonable but are others happy to defer this one?

**Comment by xstefank** [comment]
I already discussed this with @ochaloup. If he'll manage to fix this before RC2 I would merge this (assuming TCK will pass in implementation) This is not a critical change so I don't want to delay 1.0 release.
