### ISSUE TITLE
Some TCK test assertions do not report the expected versus the actual value

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#296]
For example [TckTests#joinWithOneResource](https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/TckTests.java#L537). Reporting this information provides the developer with a quicker route to tracking down the root cause.

Remark: this issue overlaps with issue #314 . However the fix for issue #314 (pr #315 ) still does not show the expected versus the actual values.

**Comment by mmusgrov** [comment]
I have marked this issue as "Waiting for feedback" because issue #314 invalidate the current issue.

**Comment by mmusgrov** [comment]
PR #315 fixed this issue so I am closing it as done.

**Comment by xstefank** [comment]
@mmusgrov the PR is not merged yet so don't close the issue, please.

**Comment by mmusgrov** [comment]
Yes but that PR fixes issue #314 which subsumes issue #296. If you take a look at #314 and also its PR (#315) you will see that the current issue is no longer required. Can you re-close this issue please.

**Comment by xstefank** [comment]
Sorry if I misunderstood. The PR contains a reference to this issue "fixes #296" in the description and it will close this issue when the PR is merged as I believe it correctly should.

**Comment by mmusgrov** [comment]
So I made it explicit in the issue description. We don't want add extra work by having multiple issues that cover the same requirement.

**Comment by xstefank** [comment]
@mmusgrov I am still not following you. "Remark: this issue overlaps with issue #314 . However the fix for issue #314 (pr #315 ) still does not show the expected versus the actual values." but as you want.

**@mmusgrov closed this as a duplicate of #314**
