### ISSUE TITLE
Fix participant responses HTTP statuses to 200 (Compensated/Completed), 202 (Compensating/Completing), and 409 (FailedToCompensate/FailedToComplete)

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#299]
... and distinguish the LRA participant outcome based on the HTTP message body:

* 200 + ParticipantStatus.Compensated / ParticipantStatus.Completed
* 200 + ParticipantStatus.Compensating / ParticipantStatus.Completing
* 200 + ParticipantStatus.FailedToCompensate / ParticipantStatus.FailedToComplete

**Comment by mmusgrov** [comment]
Note that this change was prompted by a long [discussion in the chat room](https://gitter.im/eclipse/microprofile-lra?at=5ea6f30994ac2758e30fd3af).

The title of the issue does not imply 200 in all cases (202 for example can be valid).

Note that the javadoc for Complete, Compensate, Forget and Status still contain 404's (they should be 410 GONE). Likewise, the TCK still has at least one reference to 404 (LraController, for example).

Note that this change now places a requirement on implementations to parse the response body to determine whether or not the participant performed the desired transition (ie it should not rely on the response code only). The referenced chat room discussion provided the arguments about why we have chosen the 200 OK code (even for the case where the participant has failed to compensate or complete).

**Comment by mmusgrov** [comment]
Can the body include a representation of the status:

```java
status=FailedToCompensate
```

rather than just the status value. That will ease the passage to reporting a full representation of the resource should we choose to add that in the future.

**Comment by xstefank** [comment]
@mmusgrov 

so for Completing/Compensating we will have both options 
* 200 + status
* 202

having it only with 202 would be confusing.

As for you second comment, definitely possible but would it be better to make it directly some standardized response type? Like JSON or YAML?

**Comment by ochaloup** [comment]
I consider better to use the standardized structured response than some "key=value" that needs to be parsed manually. I consider JSON as a good option here.

**Comment by rdebusscher** [comment]
There are 2 solutions on this

- The need for the addition of an entire JSON processing logic (LRA implementations did not need any JSON features yet)
- The use of a simple Pattern class from the JDK.

so key=value has my preference as this value is something 'internal' to LRA defined. Best solution is a Response header.

**Comment by ochaloup** [comment]
@rdebusscher I personally haven't weighted the point of adding the JSON features dependency in LRA. That's reasonable and would consider the JSON is not the best. The JSON sounded good to me as it's quite expandable format for key=value data.

You mentioned that the best solution for you (if I interpred it correctly) is no body but a response header. Could you elaborate on this, please? Do you mean a custom response header or different?

**Comment by rdebusscher** [comment]
Yes, a response header would not interfere with the return the developer defines in the method.


```
    @Compensate
    @PUT
    @Path("/compensate")
    public Response performRollback(@HeaderParam(LRA.LRA_HTTP_CONTEXT_HEADER) URI lraId) {
        // Perform the actual business logic for 
        return Response.ok().entity("I can return something from this call").build();
    }
```

**Comment by xstefank** [comment]
The header can indeed be extendable in the future with custom response JSON/YAML and I think it's a good idea to keep the options for users to return their own values from the participant methods so they can reuse existing endpoints. However, would it make sense to provide some utility class that would provide the correct response that the user can extend? Something like

```
    @Compensate
    @PUT
    @Path("/compensate")
    public Response performRollback(@HeaderParam(LRA.LRA_HTTP_CONTEXT_HEADER) URI lraId) {
        // Perform the actual business logic for 
        return LRAResponse.Compensated.entity("I can return something from this call").build();
    }
```
where `LRAResponse.Compensated` would be `Response.ok().header("lra-response-header-name", "compensated")`? Just to save some typing for users. but maybe it's just me that I would find this more transparent and fluent. Just an idea.

**Comment by ochaloup** [comment]
@rdebusscher I see. I like the arguments and the idea.

**Comment by mmusgrov** [comment]
> so key=value has my preference as this value is something 'internal' to LRA defined. Best solution is a Response header and not within the body.

I'm not keen on using headers to return application data. Normally the body contains a representation of a resource and clients and servers exchange resource representations. For example you cannot do content negotiation with the data that is passed in a header.

**Comment by mmusgrov** [comment]
There is still an argument for using distinct codes to avoid having to return any LRA specific content (either in a body or in a header). I know we did discuss this in the chat room but I don't believe there was a convincing argument against the use of codes:

In terms of representations and resources (sections 2 and 3 of HTTP/1.1 https://tools.ietf.org/html/rfc7231) a PUT request to the Compensate URI should put the resource into the state Compensated.

If the server knows it cannot and will never be able to update the resource state then the PUT request has failed. Returning 200 for a failed request to update the resource state seems wrong here since the HTTP RFC says "200 (OK) status code indicates that the request has succeeded". How can we justify returning 200 for a failed request?

The HTTP 1.1 RFC (https://tools.ietf.org/html/rfc7231#section-4.3.4) says:

>   When a PUT
>   representation is inconsistent with the target resource, the origin
>   server SHOULD either make them consistent, by transforming the
>   representation or changing the resource configuration, or respond
>   with an appropriate error message containing sufficient information
>   to explain why the representation is unsuitable.  The 409 (Conflict)
>   or 415 (Unsupported Media Type) status codes are suggested, with the
>   latter being specific to constraints on Content-Type values.

So the following status codes would conform with this RFC's definition of a PUT request:

200 - Compensated/Completed
202 - Compensating/Completing
409 - FailedToCompensate/FailedToComplete

**Comment by rdebusscher** [comment]
Status codes are fine for me, or data in the header (as it is not related to business data and thus doesn't belong in the body of the response - just as the HTTP status codes and message text)
