### ISSUE TITLE
Enhance the text that describes nested LRA behaviour

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#306]
The [NESTED LRA annotation element](https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/LRA.java#L351) has extra requirements beyond the ones for ['top level' LRAs](https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/ws/rs/LRA.java#L109). To facilitate safe usage of the feature we need to provide clear documentation. This task should at least include the following changes:

1. Update the javadoc for the @AfterLRA annotation to describe the meaning of the LRA_HTTP_PARENT_CONTEXT_HEADER header
2. Include a comprehensive example showing best practice when using nested LRAs.
3. Ensure that the spec examples include nesting.
4. Review the existing text around nesting to verify its accuracy, clarity and sufficiency.

**Comment by xstefank** [comment]
PR merged.
