### ISSUE TITLE
TCK won't pass on apache-cxf

### ISSUE THREAD

**Issue by idlewis** [eclipse/microprofile-lra#327]
There appears to be a difference in behaviour between the JAX-RS client from the Apache-CXF project.
When setting a request header e.g.
```
builder.header(LRA_TCK_HTTP_CONTEXT_HEADER, lraContext);
```
where builder is an InvocationBuilder, if the header value is a Java null, then Apache-CXF will set a header with a String literal value of 'null'. 
Whilst I can't prove this on my setup, I believe that using resteasy, no header is set when the header value is null.

The result of this is that the TCK fails if you try to run on top of Apache-CXF, as TckContextTests sets a null value for a number of tests. When this request gets to the test resource, the Narayana LRA implementation falls over as it tries to interpret an LRA id of 'null'

I think the Narayana implementation ought to handle the situation better, but I think the TCK should probably not be setting null values either.

**Comment by idlewis** [comment]
I've open pull request #328 with a possible fix for this

**Comment by xstefank** [comment]
PR merged.
