### ISSUE TITLE
AfterLRAListener overrides ResourceParent @Path(AFTER_LRA) but not method

### ISSUE THREAD

**Issue by paulparkinson** [eclipse/microprofile-lra#346]
ResourceParent has the following....
    @Path("/after")
    @AfterLRA
    public Response afterLRA

While it's child AfterLRAListener has...
    @Path(AFTER_LRA)
    @AfterLRA
    public Response afterEnd

The intent is to override and so would be best if the method name and not just the path were overridden. Ie...
tck/src/main/java/org/eclipse/microprofile/lra/tck/participant/api/ResourceParent.java
-    public Response afterLRA(@HeaderParam(LRA_HTTP_ENDED_CONTEXT_HEADER) URI endedLRAId, LRAStatus status) {
+    public Response afterEnd(@HeaderParam(LRA_HTTP_ENDED_CONTEXT_HEADER) URI endedLRAId, LRAStatus status) {

Probably a good idea to move the AFTER_LRA constant up into ResourceParent and reuse it from there as well as the literal is found in six different locations currently.

**Comment by spericas** [comment]
Just to follow up on @paulparkinson's comment. Without the renaming, the subclass would have two different methods with similar annotations, making the resulting JAX-RS resource model ambiguous.

**Comment by mmusgrov** [comment]
Understood. We will keep the target milestone as 1.x but we will ask implementations to add this caveat (of the JAX-RS path matching ambiguity in this particular scenario) to their release notes.
