### ISSUE TITLE
Use of enum LRAStatus as entity parameter

### ISSUE THREAD

**Issue by spericas** [eclipse/microprofile-lra#347]
The `LRAStatus` enum is used as a JAX-RS entity parameter in the spec and the TCKs. Although some JAX-RS implementations support this usage, it is _not mandated_ by the JAX-RS specification. More precisely, implementations are not required to provide an out-of-the-box message body reader to handle enums in this manner (they are required to handle enums this way associated with `*Param` injections).

I suppose it is possible to mandate LRA implementations to extend a JAX-RS implementation to support this, but this does not seem to be mentioned anywhere so I suspect the assumption made here is that all JAX-RS implementations support this, which is not the case. 

A short clarification on what is expected would be useful.

**Comment by mmusgrov** [comment]
An alternative would be to go back to using a string for returning the `LRAStatus`, the downside of doing this is that it will require users to modify their applications.

**Comment by xstefank** [comment]
@mmusgrov I expect this will need to have the spec text changes (more than just typos) and/or bigger TCK changes which means we can't include it in 2.0.

**Comment by mmusgrov** [comment]
Agreed, let's just go with Santiago's recommendation (of adding a brief note about it to the spec).

**Comment by Emily-Jiang** [comment]
In Jakarta 9.1 alignment (LRA 2.0), only javax to jakarta namespace updates are allowed with the exception of tck bug fixes, some typos. No other functional updates are allowed. If this proposed change does not impact any tck or impl updates, it can be included. Otherwise, it is better to wait after the 2.0.

**Comment by mmusgrov** [comment]
It's a spec clarification (but if people prefer moving it to milestone 2.x then that's fine with me too).

**Comment by Emily-Jiang** [comment]
> It's a spec clarification (but if people prefer moving it to milestone 2.x then that's fine with me too).
In this case, it can go into 2.0. If the team wants to move to 2.x, it is also okay.
