### ISSUE TITLE
Narayana: MicroProfile LRA 1.0 Compatible Certification Request

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#348]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Red Hat](https://www.redhat.com/en)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Narayana 5.11.1.Final](http://www.jboss.org/jbosstm/downloads/5.11.1.Final/binary/narayana-full-5.11.1.Final-bin.zip)
- [x] Specification Name, Version and download URL:<br/>
  [MicroProfile LRA 1.0](https://github.com/eclipse/microprofile-lra/releases/tag/1.0)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [MicroProfile LRA 1.0 TCK jar](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1456/org/eclipse/microprofile/lra/microprofile-lra-tck/1.0/microprofile-lra-tck-1.0.jar)
  [MicroProfile LRA 1.0 TCK jar sha1](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1456/org/eclipse/microprofile/lra/microprofile-lra-tck/1.0/microprofile-lra-tck-1.0.jar.sha1)
- [x] Public URL of TCK Results Summary:<br/>
  https://narayana.io/certifications/lra/microprofile-lra-1.0/index.html
- [x] Java runtime used to run the implementation:<br/>
  ```
  openjdk version "11.0.8" 2020-07-14
  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
  OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
  ```

  ```
  openjdk version "1.8.0_265"
  OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
  OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
  ```
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  `Linux XYZ 5.10.15-200.fc33.x86_64 #1 SMP Wed Feb 10 17:46:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by rdebusscher** [comment]
On the '_Public URL of TCK Results Summary:_' the links to the _failsafe-reports zip_ are invalid or no longer available.

>The requested URL /lra/certifications/microprofile-lra-1.0/lra-1.0-jdk-8-ccr-results.zip was not found on this server.

**Comment by xstefank** [comment]
Thanks @rdebusscher. I missed that paths were updated after the CCR was published, the links are working now.

**Comment by mmusgrov** [comment]
This one is complete so I will close it.
