### ISSUE TITLE
Use ChronoUnit instead of TimeUnit

### ISSUE THREAD

**Issue by xstefank** [eclipse/microprofile-lra#57]
As stated by Emily [1] we should use ChronoUnit instead of TimeUnit to stay aligned with other MicroProfile specifications.

[1] [https://github.com/eclipse/microprofile-lra/pull/50/files#r238217979](https://github.com/eclipse/microprofile-lra/pull/50/files#r238217979)

**Comment by mmusgrov** [comment]
@xstefank I will take this since a separate PR will clash with my #50

**Comment by xstefank** [comment]
@mmusgrov sure, no problem, can you assign yourself/others now to the issues?

**Comment by xstefank** [comment]
Should be resolved by 46e8a95018253b3cbea4375f0a89ad07b5be35bd
