### ISSUE TITLE
TCK tests time limits should be configurable

### ISSUE THREAD

**Issue by ochaloup** [eclipse/microprofile-lra#60]
The TCK tests use the timeout which should be configurable. Even the timeout for the TCK is set to 50000 ms (https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/TckTests.java) it could be run on arbitrary fast machine. There is another hardcoded time limit values like at https://github.com/eclipse/microprofile-lra/blob/master/tck/src/main/java/org/eclipse/microprofile/lra/tck/participant/api/ActivityController.java#L502 where `renewTimeLimit` requires processing being done in 100ms. That could be difficult on a slower machine.

The time limits and timeouts should be configurable. Possibly with some time out factor as j2ee tck does.

**Comment by xstefank** [comment]
@mmusgrov this shouldn't be closed, the referenced commit is for issue #61 where Rudy mentioned he made a typo. This should be reopened.

**Comment by rdebusscher** [comment]
Wrongly closed by commit message.

**Comment by mmusgrov** [comment]
@ochaloup #42 will remove the properties for the coordinator endpoint which we will need to run the TCK. We need to be able to obtain the equivalent information from the config proposal you are working on.

**Comment by ochaloup** [comment]
I created PR https://github.com/eclipse/microprofile-lra/pull/87 which is about to provide configuration for the timeout.

**Comment by mmusgrov** [comment]
@ochaloup Since https://github.com/eclipse/microprofile-lra/pull/87 is now merged, is it okay to resolve this issue?

**Comment by mmusgrov** [comment]
@ochaloup I think I am correct in assuming that PR #87 also fixed this current issue in which case I will close this issue. If my assumption is incorrect then please reopen it.
