### ISSUE TITLE
@Compensate method could be invoked during the service is ongoing when timeout happens

### ISSUE THREAD

**Issue by zhfeng** [eclipse/microprofile-lra#64]
We have an [issue](https://github.com/apache/servicecomb-pack/issues/346) from the ServiceComb community which describes the timeout scenario.  I just use the LRA annotation with the following snippet codes

```
@LRA(timeoutLimit = 5)
void ShouldTimeoutService(@LRAId id) {
       // This service will be timeout after 5 minutes and 
       // the following insert order could run after the compensate method.
      sleep(10);
      orderService.insert(new Order(id, "COMFIRM")); 
}

@Compensate
void cancel(@LRAId id) {
      Order order = orderService.getOrder(id);
      if (order != null) {
           orderService.cancel(order);
      }
}
```

if the orderService.insert() is running but has not insert the order, and the timeout happens, the LRA is cancelled by the coordinator. The compensate method is invoked but not find the order, so it can not cancel the order. When the whole transaction ends, the orderService create a new order in the database which is not expected.

1. The coordinator needs to guarantee the compensate method  should be invoked after the business service is finished.It is not clear described at the [LRA spec timeout](https://github.com/eclipse/microprofile-lra/blob/master/spec/src/main/asciidoc/microprofile-lra-spec.adoc#timing-out-lras-and-compensators).
2. The *cancel(@LRAId id)* needs to throw the exception when failing to find the order or returns the COMPENSATE_FAIL, and the coordinator will retry to invoke it.

So I wonder to discuss which option could be more reasonable here and thanks for any inputs !

**Comment by xstefank** [comment]
Hi @zhfeng, I think what you are describing that `@Compensate` needs to wait for the order to be persisted. For this reason `@Compensate` can indicate to the coordination that it is still 'Compensating' after the `@Compensate` method invocation:

> If the resource cannot perform a compensation activity immediately the @Compensate method SHOULD do one or more of the following:
> 
> * return CompensatorStatus.Compensating
> 
> * return a 202 Accepted HTTP status code
> 
> * mark the method as a JAX-RS asynchronous method (using the javax.ws.rs.container.Suspended annotation).
> 
> In each case it MUST provide an @Status method that reports the progress of the compensation. The only case where the @Status method is not mandatory is if the compensation activity cannot fail.
> 

The spec also states:

> Fail: the client has cancelled the LRA and the activity has completed unsuccessfully. All participants that are registered with the LRA will be invoked to perform compensation in the reverse order [1]. The LRA forgets about all participants that indicated they operated correctly. Otherwise, compensation may be attempted again (possibly after a period of time) or alternatively a compensation violation has occurred and must be logged

So basically the coordination can:
a/ repeatedly call `@Compensate` in case there is no `@Status` endpoint exposed and `@Compensate` is idempotent or
b/ repeatedly call `@Status` endpoint which should report the status of the compensation
until it will be successfully compensated or the compensation fails which are states of the participant depicted in the spec.

Hope this helps.

**Comment by zhfeng** [comment]
Thanks @xstefank it is clear.
