### ISSUE TITLE
Invocation time of @Complete method 

### ISSUE THREAD

**Issue by WillemJiang** [eclipse/microprofile-lra#65]
According the annotation description of @Complete, the method should be invoked if the LRA is closed. Will the method be invoked when the If LRA is cancelled?  If the answer is yes, will it be invoked when the compensation method is called.

The background story is we use some kind of lock to prevent the resource be used by LRA twice, so we introduce the lock on the method of LRA, and release the lock on the Completed method.  If the completed method is called whenever the LRA method is succeed or cancelled, we could put the  release lock code into the completed method.

**Comment by mmusgrov** [comment]
@WillemJiang Can we close this now or would you prefer that we added some further clarifying text to the specification.

**Comment by WillemJiang** [comment]
@mmusgrov Thanks for the explanation, I think the specification is clear enough. For my case, I can live with clean up the resource lock in both of these two methods.
