### ISSUE TITLE
Ensure the semantics of context propagation are clear

### ISSUE THREAD

**Issue by mmusgrov** [eclipse/microprofile-lra#7]
If you have a microservice A that wants to participate in an LRA and calls microservice B (which does not have specific LRA behaviour) and this calls microservice C (which does have specific LRA behaviour), then B should not need to be annotated with @LRA. The spec should be clear that is the defined behaviour.

**Comment by mmusgrov** [comment]
PR was merged

**Comment by rdebusscher** [comment]
Reopened.

The `always propagate Context Header` is counter intuitive and does not allow to call an endpoint which doesn't have the Context header (when one is present)

**Comment by rdebusscher** [comment]
The proposal is to define a configuration parameter to activate such propagation under all circumstances.

Note, the propagation of the LRA context is ALWAYS perform within an LRA context (JAX-RS method is annotated with @LRA except for @LRA.Type.NOT_SUPPORTED as this type means what you do not have an LRA context active)

**Comment by rdebusscher** [comment]
No Consensus in trying to make this better.
