### ISSUE TITLE
Define behaviour when @LRA annotated method throws an exception

### ISSUE THREAD

**Issue by ochaloup** [eclipse/microprofile-lra#84]
The specification defines that a method annotated with `@LRA` finishes the LRA (either with `complete` or `cancel`). There is not defined what happens when such method is ended by a thrown exception.
It would be good to define this behaviour.

JTA java developers are used to how the JTA works in way that `RuntimeException` rolls-back the transaction while the checked exceptions do not. The CDI [@Transactional](https://docs.oracle.com/javaee/7/api/javax/transaction/Transactional.html#rollbackOn--) defines what are exceptions that rolls-back the transaction then. The similar approach could be taken for @LRA as well.

**Comment by ochaloup** [comment]
on discussion on meeting 2019-02-04: any exception thrown from the `@LRA` annotated method cancel the LRA. The `cancelOn`/`cancelOnFamily` controls to `cancel` the LRA based on the error code returns from the `@LRA` annotated method which is the REST endpoint.

**Comment by ochaloup** [comment]
I was thinking to create a PR on this but I found one case I'm not sure how that should be handled. What if the exception is thrown from the method which does not started the LRA context.

```java
// -> incoming LRA context with already started LRA
@LRA(Type.SUPPORTS)
public void method() {
  throw new RuntimeException();
}
```

Will this cancel the LRA context which came from outer space? Or throwing the exception will cause to cancel the LRA only when started at the same method?

**Comment by xstefank** [comment]
@ochaloup I believe that depends on the value of the `end` attribute of the `@LRA` annotation

**Comment by ochaloup** [comment]
If you have non-exception case like microservice A calls a microservice B then

```
@LRA(Type.REQUIRES_NEW)
public void microserviceAMethod() {
   ClientBuilder.newClient().target(<<microserviceBMethod>>).post();
}

@LRA(Type.SUPPORTS, end = true)
public void microserviceBMethod() {
  // do some business logic
}
```

The `end` is by default to `true`, this fact is emphasized at the `microserviceBMethod`. When the `microserviceBMethod` and returns back to microservice B the LRA is not ended. The LRA will be ended at the end of the `microserviceAMethod`. It means the responsibility for ending the LRA is on he method that started the original context. How is it with exception that would be thrown in `microserviceBMethod`. Will the microservice B cancel the LRA even it only received the context and the B does not start it? Or it should be responsibility of microservice A (`microserviceAMethod` to handle the error codes and then decides to throw an exception (and cancel the LRA) or ignore the errors?

**Comment by rdebusscher** [comment]
I'm not sure about your reasoning of the ending of the LRA. SUPPORTS has the following definition

`If called inside a LRA context the managed bean method execution must then continue inside this LRA context.
`

Since it executes inside the LRA context started by `microserviceAMethod`, the end means that the `microserviceBMethod` closes the LRA context which was started by `microserviceAMethod`.

If you want that `microserviceAMethod` has complete control over the LRA, the SUPPORTS should be replaced with NOT_SUPPORTED. Then the `microserviceAMethod` can decide what to do with the LRA based on the return value (including exceptions) it receives from `microserviceBMethod`.

**Comment by rdebusscher** [comment]
The only special case is when we throw a `WebApplicationException`.

In thtat case, we need to take the value of the **status** (`getResponse().getStatus()` ) and see if the value is covered by any on the `cancelOn` or `cancelOnFamily` values and decide on that if the LRA needs to be cancelled or not.

**Comment by mmusgrov** [comment]
+1

**Comment by ochaloup** [comment]
The decision on the meeting was that

- exceptions thrown from the method are not about to be specially handled by the LRA
- the default `cancelOnFamily` will be defined to contain `4xx` and `5xx` errors
- even there is no special handling to be mentioned in the spec, there should be a mentioned that:
-- is expected that by default the `RuntimeException` is transformed by the JAX-RS exception mapper to the `5xx` error code. It's not the defined elsewhere in specification but it's usual behaviour. We expect that the implementation will transform the `Exceptions` to `5xx` code which should cause cancelling the LRA at the end.
-- when the framework itself does not map the exceptions in this way (aka `RuntimeException` is not mapped to `5xx`) it could be required to add separate exception mapping.
-- the user should consider this error code handling especially when he use the [MP Fault Tolerance](https://github.com/eclipse/microprofile-fault-tolerance)

**Comment by xstefank** [comment]
+1 just one comment:

> * the default `cancelOnFamily` will be defined to contain `4xx` and `5xx` errors

I believe that decision was only 5xx - https://docs.google.com/document/d/1HBPiXpsXcQp9T8JeoT-IDs-EblZX1SxuTV5qjUPzwrM/edit#bookmark=id.bqi49xey9iw9

**Comment by ochaloup** [comment]
@xstefank I wanted to mostly clarify what is in spec already (see
https://github.com/eclipse/microprofile-lra/blob/master/api/src/main/java/org/eclipse/microprofile/lra/annotation/LRA.java#L197)

I think the `4xx` and `5xx` are correct to be default for `cancelOnFamily`.

If you get `4xx` where the error code means `bad request` or `not processable` I argue it should be still canceled
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

if I summarize my understanding of the `cancelOn/cancelOnFamily` meaning then (it would be good to be clarified in spec too): the @LRA is the JAX-RS method, if that method returns the paritcular error in the `Response` then the LRA is cancelled. Otherwise the LRA is finished (completed).

I'm not sure if the `4xx` error code should mean completion.

**Comment by xstefank** [comment]
@ochaloup +1

**Comment by mmusgrov** [comment]
The javadoc for cancelOnFamily says:
```java
     * The cancelOnFamily element can be set to indicate which families of
     * HTTP response codes will cause the current LRA to cancel. By default client
     * errors (4xx codes) and server errors (5xx codes) will result in
     * cancellation of the LRA.
```

I think the fix should ensure that default corresponds to this javadoc
